travis:
  secure:
    BINSTAR_TOKEN: HU98Oms825U6/4nsIwiH7vmpIFTn4YNu2h5YrJb0tqKYCgvo0Vgx5qvGyvAOzvCKQmKKHgGhN7BVrXrSt9kRqkBaAZggX0kvQCwLFA1dL/Eear40FQNR4Hg/l7WAQ3SFcTJZ/7gCjBqCXu+fHikenAZGFRt3xnTw2EbPriFRAPZm3lhkOPhvDikxUZwa7fPa/GIQ38EtyPjoaaqS3aOWJPcg4Lu/jiRiLJSkreNX+OaJrNhPdEvcbWhndq3xo51BMSMSpL8QeEwKLnBwiy524Pvjc6pzGKhXui9kQlY5A1yFOY81+KxYGgfYTWEYrRS3lyppIotlDzW8cGrdJVKJajUWBlTodPoxnWnxmAdapzG5eZK3tVjBWEF/y58fgzQXSMA0SVzYwCvRfIyU+vFzxXgqEV6Ag/5iSbjrnmKLVa+miTh71GlQIKNj/9QEVbuca1CNRWLSI2anxmrMxWvD5gjwoRr2BgF9+5XiJwxlPZ1pnMAAEZzDQLRbz/Y+tVJ4BMrH+yNhiWrxig50tCFoTLpuNIIRJlp/qBfQhQdiBdGZtaFHKdxacvSHQf58+9I6aSW3qC7REnLTdkfAhI7+Vki5dI/zRi5hL6uhlVEuKDy3Pv8i21q2F42xOInMdUGkWxBpH75FWIRp8+MYVGPBxB0BoBlEwApONGjvLnaG1uU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
