travis:
  secure:
    BINSTAR_TOKEN: Pajuk+E3Yw3MVSxXNZlhOb23nm4qo0PCtJ1QiOieVcIcLstmpfT0L9FArjoYCJ+W/iGccHhnEyQHMGbc3anXNwlJvmrKAIkAdeqEgdJoX/2uZhoWJoduwnFOX6K+yhkN7ULP4Mmrjlh+jv8+O8FcIU9aXVCVbk7DRn3nEf1/LnxxwYR6025a532vCX82bV4GonBy9i4xhzZX6lTJRZrxS+BOQcJWCeADiOVIBplcBkDq9tXhQCyRkiXceOTV0G8L1sH3XUGoPUSlO6WC/26v3fpL+NCqG1d6xauzap6CXve8rEqxZrSIipabdWhWBS6ysbhZq1XjS0bvEHELSbCae1nBOTB/pP5xH+GLLq8A37UvF7L3j6CsfYJ+KQImyntsYa+mqGfGew8lSjQcdDEHm1OaRGa5BeKr7NbPM3XO0LoXb06SJA4khtJe+t4QHCO/emmO1dsy3N1sloQ0sNcmrvE+K9siRdNeA2u2EKDtgdodmn0d9PaEu2PUMbyAPyqYTS/USFUZ/juuX6puokhoDzyQB9HIlH+gIm/N/YZMTufMb1quofQj+g7gZZLAefr9sXy7jEzag4CkQuNTRFI+V0cF6/easMvPJMeCOMip28rqCXOZAMTJDJKayyFotz3+KD7JpLAYmKhsrJ16aY6U4aMBre8QNUsZj8cWw2EMIdo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
